### ISSUE TITLE
Es de las lógicas de esta entrega, más limpia, clara y ordenada que me han entregado! sigue así!

### ISSUE THREAD

**Issue by itacademyReact** [MireiaBS/SPRINT-5-APIS#4]
https://github.com/MireiaBS/SPRINT-5-APIS/blob/83ce5c2c83f776cf83b4be674896b3d36754e438/js/main.js#L105

**Comment by MireiaBS** [comment]
Muchas gracias!! Tendré en cuenta los tips que me has dejado! :)
